# Source: unguard/templates/like-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-like-service
  labels:
    app.kubernetes.io/name: like-service
    app.kubernetes.io/part-of: unguard
    
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: like-service
      app.kubernetes.io/part-of: unguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: like-service
        app.kubernetes.io/part-of: unguard
        
    spec:
      containers:
        - name: like-service
          image: ghcr.io/dynatrace-oss/unguard/unguard-like-service:0.9.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SERVER_PORT
              value: "8000"
            - name: API_PATH
              value: "/like-service"
            - name: USER_AUTH_SERVICE_ADDRESS
              value: "unguard-user-auth-service"
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: unguard-mariadb
                  key: mariadb-root-password
            - name: JAEGER_SERVICE_NAME
              value: "unguard-like-service"
