# Source: unguard/templates/redis.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: unguard
    
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/part-of: unguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: unguard
        
    spec:
      containers:
        - name: redis
          image: redis:5.0
          command:
            - redis-server
            - "/config/redis.conf"
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          readinessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          livenessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-data
            - mountPath: /config
              name: config
          resources:
            limits:
              memory: 512Mi
              cpu: 125m
            requests:
              cpu: 70m
              memory: 200Mi
      volumes:
        - name: redis-data
          emptyDir: { }
        - name: config
          configMap:
            name: unguard-redis-config
            items:
              - key: redis-config
                path: redis.conf
