# Source: unguard/templates/membership-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-membership-service
  labels:
    app.kubernetes.io/name: membership-service
    app.kubernetes.io/part-of: unguard
    
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: membership-service
      app.kubernetes.io/part-of: unguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: membership-service
        app.kubernetes.io/part-of: unguard
        
    spec:
      containers:
        - name: membership-service
          image: ghcr.io/dynatrace-oss/unguard/unguard-membership-service:0.9.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: SERVER_PORT
              value: "8083"
            - name: API_PATH
              value: "/membership-service"
            - name: MARIADB_SERVICE
              value: "unguard-mariadb"
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: unguard-mariadb
                  key: mariadb-root-password
