# Source: unguard/templates/status-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-status-service
  labels:
    app.kubernetes.io/name: status-service
    app.kubernetes.io/part-of: unguard
    add: 3
    
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: status-service
      app.kubernetes.io/part-of: unguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: status-service
        app.kubernetes.io/part-of: unguard
        
    spec:
      serviceAccountName: unguard-status
      containers:
        - name: status-service
          image: ghcr.io/dynatrace-oss/unguard/unguard-status-service:0.9.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: API_PATH
              value: "/status-service"
            - name: KUBERNETES_NAMESPACE
              value: "unguard"
            - name: IGNORED_DEPLOYMENTS # add deployments to ignore separated by spaces
              value: "unguard-user-simulator"
            - name: MARIADB_SERVICE
              value: "unguard-mariadb"
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: unguard-mariadb
                  key: mariadb-root-password
