# Source: unguard/templates/user-auth-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-user-auth-service
  labels:
    app.kubernetes.io/name: user-auth-service
    app.kubernetes.io/part-of: unguard
    
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: user-auth-service
      app.kubernetes.io/part-of: unguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-auth-service
        app.kubernetes.io/part-of: unguard
        
    spec:
      containers:
        - name: user-auth-service
          image: ghcr.io/dynatrace-oss/unguard/unguard-user-auth-service:0.9.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
          env:
            - name: SERVER_PORT
              value: "9091"
            - name: MARIADB_SERVICE
              value: "unguard-mariadb"
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: unguard-mariadb
                  key: mariadb-root-password
            - name: JAEGER_SERVICE_NAME
              value: "unguard-user-auth-service"
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent"
            - name: JAEGER_SAMPLER_TYPE
              value: "const"
            - name: JAEGER_SAMPLER_PARAM
              value: "0"
            - name: JAEGER_DISABLED
              value: "true"
