# Source: unguard/templates/payment-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-payment-service
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: unguard
    
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-service
      app.kubernetes.io/part-of: unguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payment-service
        app.kubernetes.io/part-of: unguard
        
    spec:
      containers:
        - name: payment-service
          image: ghcr.io/dynatrace-oss/unguard/unguard-payment-service:0.9.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SERVER_PORT
              value: "8084"
            - name: API_PATH
              value: "/payment-service"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=unguard-payment-service"
            - name: OTEL_TRACES_EXPORTER
              value: "none"
            - name: OTEL_EXPERIMENTAL_SDK_ENABLED
              value: "false"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger-collector:4318"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_PROPAGATORS
              value: "jaeger"
            - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
              value: "false"
            - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
              value: "python"
